name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行
  workflow_dispatch:      # 手動実行も可能

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: PublicBoy01
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push generated files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output  # 👈 output ブランチに SVG を push
